version: '3'
services:
  postgres:
      image: postgres
      container_name: course_api
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
      ports:
        - 5432:5432